[tool.poetry]
name = "stock-fast-api"
version = "1.3.0"
description = ""
authors = ["seria <seria.ati@gmail.com>"]
license = "GPL-v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.9.1"
fastapi = "^0.109.0"
tortoise-orm = "^0.20.0"
fake-useragent = "^1.4.0"
uvicorn = "^0.27.0"
python-dotenv = "^1.0.1"
asyncpg = "^0.29.0"
seria-library = {git = "https://github.com/seriaati/seria-library"}


[tool.poetry.group.dev.dependencies]
ruff = "^0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
